const ConversationStages = {
  INTRODUCTION: "INTRODUCTION",
  DATA_REQUEST: "DATA_REQUEST",
  ACTION_REQUEST: "ACTION_REQUEST",
  ACTION_CONFIRMATION: "ACTION_CONFIRMATION",
  TAKE_ACTION: "TAKE_ACTION",
  CONCLUSION: "CONCLUSION"
};

module.exports = { ConversationStages }